### ISSUE TITLE
why ım getting this issue What should I do? Do I need to install dogecoin core?

### ISSUE THREAD

**Issue by aslanmurat4565** [sirduney/dunes-cli#2]
node dunes.js wallet new
C:\Users\samsung\Desktop\doge\dunes-cli\dunes.js:297
  for (let i = 0; i < inputString.length; i++) {
                                  ^

TypeError: Cannot read properties of undefined (reading 'length')
    at stringToCharCodes (C:\Users\samsung\Desktop\doge\dunes-cli\dunes.js:297:35)
    at Object.<anonymous> (C:\Users\samsung\Desktop\doge\dunes-cli\dunes.js:35:20)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
    at node:internal/main/run_main_module:28:49

Node.js v20.10.0

**Comment by GreatApe42069** [comment]
run command 
 npm install
 
 then 
 npm fund
 
 then 
 npm audit
 
 last run 
 npm fix
 
 should be good to go

**Comment by sirduney** [comment]
Thanks @GreatApe42069 closing
